### ISSUE TITLE
Feature Request: Make links open outside the client

### ISSUE THREAD

**Issue by shiv19** [sean-perkins/discourse-forum-client#3]
Currently, all links just open inside the client.
For example, a GitHub URL. And once you click on them, there is no visible way for the user to navigate back.

Is it possible to make all links open in default browser?

**Comment by sean-perkins** [comment]
With 1.1.1 there should be a back navigation (with prev/next) after navigating. 

![screen shot 2017-11-01 at 6 03 05 pm](https://user-images.githubusercontent.com/13732623/32300237-efd7b3c6-bf2e-11e7-8652-717c9a89f064.png)

I feel like's an easier workflow than moving the user into their browser... but I could make a settings panel to configure a feature like this.

**Comment by shiv19** [comment]
Yes, with 1.1.1 back navigation is available. cheers!
