### ISSUE TITLE
Typo in the about section of v1.1.1

### ISSUE THREAD

**Issue by shiv19** [sean-perkins/discourse-forum-client#4]
<img width="284" alt="screen shot 2017-11-02 at 1 59 27 am" src="https://user-images.githubusercontent.com/9407019/32296183-8ba90970-bf71-11e7-9170-1cdd4f4eeff1.png">
It says 1.0.0
The zip file I downloaded was of 1.1.1

**Comment by sean-perkins** [comment]
In addition to this task:
- Should add the version number in the lower left-hand corner of the app.
