### ISSUE TITLE
Bug: Back Navigation button disappears

### ISSUE THREAD

**Issue by shiv19** [sean-perkins/discourse-forum-client#7]
Steps to recreate.
1. Open any link inside the forum client which takes you to other websites.
2. Now, instead of clicking back button, click on the NativeScript logo, (or the forum logo, to which you are logged in)

What I expect to happen,
> User should be taken back to homepage of the forum

The current behavior
> The back navigation button disappears.

Additional notes.
This also happens in any place in the client where you see the back button (no need to go to external site).

**Comment by sean-perkins** [comment]
The forward/back buttons inside the client are displayed solely on the webview's hooks for if the browser `canGoBack` or `canGoForward`. By going back to the root, I assume it's calculating the original URL matches the current URL and that new history exists. 

There might not be a lot available here, outside of managing the URL changes locally and writing a custom decision tree around it. I really would like to avoid tracking user's information inside the client though.

**Comment by shiv19** [comment]
Instead of tracking user information, can we not make it so that, clicking on the icon in the sidebar, always takes the user to the forum's homepage?

**Comment by sean-perkins** [comment]
The icons in the side bar should always take you back to the URL that you entered inside of the pop-up modal when adding the site. 

I had added a patch in the later releases for tapping the same active item, as you are already viewing: 
https://github.com/sean-perkins/discourse-forum-client/blob/master/app/containers/App.tsx#L26

Is that not working as expected? 

Edit:

Ahh - I am clearing history when you tap the menu item again. Is that what you are referring to with the NativeScript Logo? Not the forum's logo, but your custom icon?

**Comment by shiv19** [comment]
Yes the logo on the side bar of the client. Not the logo of the forum.
When I click that, it doesn't take to homepage.
